project_id = "qhsvmfnjoowexmyaqgrr"

[functions.analyze-threats]
verify_jwt = false

[functions.analyze-media]
verify_jwt = false

[functions.green-api-webhook]
verify_jwt = false

[functions.green-api-fetch]
verify_jwt = false

[functions.green-api-qr]
verify_jwt = false

[functions.green-api-partner]
verify_jwt = false
